-- 001_init.sql
-- Initial workspace bootstrap script

prompt Creating sample baseline objects...

-- Example: create a simple health-check table (ignore ORA-00955 if it already exists)
begin
  execute immediate q'[
    create table app_health_check (
      id number generated by default as identity primary key,
      status varchar2(30) not null,
      checked_at timestamp default current_timestamp not null
    )
  ]';
exception
  when others then
    if sqlcode != -955 then
      raise;
    end if;
end;
/

insert into app_health_check (status) values ('READY');

commit;

prompt Baseline script complete.
